### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by sgtpepper43** [seadlng/seadlng#45]
We need a favicon.

**Comment by Jargonius** [comment]
Here are some options:
*https://www.iconfinder.com/icons/67589/leaf_plant_icon#size=16
https://www.iconfinder.com/icons/130287/plant_icon#size=60
http://www.iconarchive.com/show/christmas-shadow-2-icons-by-pelfusion/Tree-icon.html

I can update comments not owned by me... said Trevor

**Comment by sgtpepper43** [comment]
I like the happy tree, but only if it's the right color
