### ISSUE TITLE
Idea Edit Lock

### ISSUE THREAD

**Issue by sgtpepper43** [seadlng/seadlng#47]
We need to decide when exactly summaries should be locked, after which only appending is allowed.  

Possibilities:
- After branch creation
- After branch merged
- After comments made  

Or a combination thereof

**Comment by Jargonius** [comment]
I think it should be after branch creation.  But to clarify, does the second option mean that they can edit it until after they merge in a branch?

**Comment by sgtpepper43** [comment]
Yeah, that's what it would mean. But I think after branch creation should be the way. I was thinking after comments also, but nah, comments can be edited.

**Comment by Jargonius** [comment]
Should this be closed then?  We decided the answer.
