### ISSUE TITLE
Define User Schema

### ISSUE THREAD

**Issue by sgtpepper43** [seadlng/seadlng#5]
Note: Question marks just mean that it's boolean
### So far:
- name
- email
- role
- hashedPassword
- provider (passport provider, ie local, google, facebook, etc)
- salt

should we keep an object that references all of the user's ideas? Considering that it's a document database we probably should, we don't want to be searching through all the ideas.

to add:
- ideas (created, commented, etc) (also, just the id's)
  - favorite?
  - following?
- Image (or just use gravatar... github only just let users upload images today, so, yeah. Or we can use CATATAR)

**Comment by Jargonius** [comment]
I think we should do this.  I don't see why not for favorites and following.
